### PR TITLE
Added documentation for un-manage cluster REST endpoint

### PR DESCRIPTION
**Pull request by shtripat**
tendrl-bug-id: Tendrl/api#360
Signed-off-by: Shubhendu <shtripat@redhat.com>

### CODE REVIEW

**Comment by shtripat** [comment]
@r0h4n @nthomas-redhat @gnehapk @fbalak plz review

**Comment by shtripat** [comment]
Ack. I will place this after description of import cluster.
Also regarding #365 actually there is no fix required I feel and we need to pass a `-d "{}"` in the request.

**Comment by shtripat** [comment]
@r0h4n done the required changes

**Comment by r0h4n** [comment]
@Tendrl/api please review and merge  (create a merge commit)

**Pull request merged**
