### PR TITLE
Corrected cluster/:cluster-id/profiling to submit a job

### PR DESCRIPTION
**Pull request by shtripat**
tendrl-bug-id: Tendrl/api#405
Signed-off-by: Shubhendu <shtripat@redhat.com>

### CODE REVIEW

**Comment by shtripat** [comment]
@shirshendu this PR gives the below error though

```
2018-03-18 01:46:58 - NoMethodError - undefined method `[]' for nil:NilClass:
        /usr/share/tendrl-api/lib/tendrl/flow.rb:17:in `initialize'
        /usr/share/tendrl-api/app/controllers/clusters_controller.rb:111:in `new'
        /usr/share/tendrl-api/app/controllers/clusters_controller.rb:111:in `block in <class:ClustersController>'
```

Not sure how to resolve this. Please help.

**Comment by shirshendu** [comment]
@shtripat https://github.com/Tendrl/gluster-integration/blob/master/tendrl/gluster_integration/objects/definition/gluster.yaml needs description of `EnableDisableProfiling`, right?

**Comment by shtripat** [comment]
>>  Please sign your commits

Its already signed off by `Shubhendu <shtripat@redhat.com>`

>>  Please add API documentation

The one at `http://127.0.0.1/api/1.0/clusters/9a4b84e0-17b3-4543-af9f-e42000c52bfc/profiling` is the actual API for this and its present in document already

>>  Please commit updated flow definition (with EnableDisableProfiling) to gluster-integration repo

Its added as part of GI PR `https://github.com/Tendrl/gluster-integration/pull/593`

>>  Please add updated gluster.yaml to this PR, at spec/fixtures/definitions/gluster.yaml

Done

**Comment by shtripat** [comment]
Tested the API and it submits the job as expected for enable/disable volume profiling at cluster level.

**Comment by shirshendu** [comment]
@shtripat Some more comments:
- `signed-off-by` is not the same as signing commits: https://help.github.com/articles/signing-commits-using-gpg/ -- This is required for the merge button on github to activate.
- The build is failing because you need to update the spec in `spec/controllers/clusters_controller_spec.rb:109` - PUT with POST, since you changed the method in the controller.

**Pull request merged**
