### PR TITLE
Remove password_confirmation requirement

### PR DESCRIPTION
**Pull request by shirshendu**
This is backward-compatible because unknown parameters are simply
ignored.

Fixes: #106

### CODE REVIEW

**Comment by shtripat** [comment]
Code looks fine. @gnehapk does UI already have a equality check for passwords in UI? If not we need to add that I feel.

**Comment by gnehapk** [comment]
@shtripat Yes, we do check it in UI. @shirshendu Does this change also require to remove `password_confirmation` property from request data while creating user from UI?

**Comment by shirshendu** [comment]
@gnehapk No, this change is backward compatible. it will silently ignore the `password_confirmation` property.

**Comment by shirshendu** [comment]
@gnehapk It works for create as well as edit; you don't need to send `password_confirmation` in any user-related API.

**Pull request merged**
