### PR TITLE
Unify building process and fix bogus date issue

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
tendrl-bug-id: Tendrl/api#202
Signed-off-by: Timothy Asir J <tjeyasin@redhat.com>

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@r0h4n , @dahorak , @anivargi, Please review

**Comment by dahorak** [comment]
If I understand it correctly, this will put the `*src.rpm` package to `~/rpmbuild/SRPMS/` directory, right? 

Would it make sense to copy/move the srpm package to the working directory?
In the meaning, that other Tendrl packages are send to copr by command similar to this:
```copr-cli build release tendrl-alerting*src.rpm```
But for api we will have to use slightly different path:
```copr-cli build release ~/rpmbuild/SRPMS/tendrl*src*rpm```

I'm not sure if it is the right approach, I'm just asking.

**Comment by mbukatov** [comment]
> If I understand it correctly, this will put the *src.rpm package to ~/rpmbuild/SRPMS/ directory, right?

This seems fine to me, that path is the default used by rpmbuild. I don't think we need to override that or copy the source rpm package somewhere else before pushing into copr.

**Comment by dahorak** [comment]
@mbukatov I know, that `~/rpmbuild/SRPMS/` is the default target for rpmbuild, my question is more about the fact, that for other Tendrl packages are the srpm placed to the working directory, so if it will be the same for _api_ package, it will be slightly easier and more clear for automation.

**Comment by mbukatov** [comment]
> ... other Tendrl packages are the srpm placed to the working directory, so if it will be the same for api package, it will be slightly easier and more clear for automation.

@dahorak Ah, sorry for misunderstanding. This unification would make sense.

**Comment by anivargi** [comment]
@TimothyAsir is this good to merge?

**Comment by dahorak** [comment]
When this will be merged to master/release branch?

**Comment by TimothyAsir** [comment]
@anivargi yes this patch is good to merge!

**Pull request merged**
