### PR TITLE
Corrected the name of parameters

### PR DESCRIPTION
**Pull request by shtripat**
Signed-off-by: Shubhendu <shtripat@redhat.com>

### CODE REVIEW

**Comment by shtripat** [comment]
@shirshendu plz review

**Comment by shirshendu** [comment]
Please see discussion [here](https://github.com/Tendrl/api/issues/391) and [here](https://github.com/Tendrl/commons/issues/870). We need to be doing validation from master definitions, and not adding per-api validations. I'm already looking into that.

**Comment by r0h4n** [comment]
@shirshendu The validations wont be part of 3.4 downstream, we need to review/merge this PR as a short term solution

**Comment by shirshendu** [comment]
https://github.com/Tendrl/api/pull/396

**Pull request closed without merging**
