### PR TITLE
Fix rpmlint error

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@r0h4n , @anivargi , @nthomas-redhat , Please review

**Comment by TimothyAsirJeyasing** [comment]
This patch will fix rpmlint errors and most of the warnings for rubygem-bundler reported by https://ci.centos.org/view/Tendrl/job/tendrl-0-1-package-validation-rpmlint/429/testReport/usmqe_tests.rpm/test_rpm/test_rpmlint_rubygem_bundler_/

**Comment by anivargi** [comment]
@TimothyAsir please add only the change commit, I see different commits, also fix the merge conflicts.

**Comment by r0h4n** [comment]
Please send the PR on "master" branch

**Pull request closed without merging**
