### PR TITLE
Reload the systemd process to use updated tendrl-apid service conf

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
Signed-off-by: Timothy Asir J <tjeyasin@redhat.com>

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@brainfunked , @anivargi , Please review

**Comment by brainfunked** [comment]
Why is the daemon reload in the post section of the httpd sub package?

**Comment by TimothyAsirJeyasing** [comment]
Sorry, i have't noticed, I will move it to api

**Comment by r0h4n** [comment]
Please send the PR on "master" branch

**Pull request closed without merging**
