### PR TITLE
Renamed tendrl-ssl.conf.sample to tendrl-ssl.conf.sample

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
bugzilla: 1677307
tendrl-bug-id: Tendrl/api#458

Signed-off-by: GowthamShanmugasundaram <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
@shtripat @nthomas-redhat @dahorak @mbukatov

**Comment by GowthamShanmugam** [comment]
I verfied

**Comment by GowthamShanmugam** [comment]
@mbukatov please review

**Comment by dahorak** [comment]
run build

**Comment by GowthamShanmugam** [comment]
@shtripat we can merge this PR

**Pull request merged**
