### PR TITLE
Load_all function required job_id in job json which is created by API

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
tendrl-bug-id: Tendrl/api#433
bugzilla: 1592487

Signed-off-by: GowthamShanmugasundaram <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
@shtripat @shirshendu @nthomas-redhat @r0h4n please review

**Comment by GowthamShanmugam** [comment]
I saw Travis result, all green

**Comment by shtripat** [comment]
LGTM. Approved

**Comment by shirshendu** [comment]
@shtripat I can't merge this until you mark the review as approved on github: https://help.github.com/articles/approving-a-pull-request-with-required-reviews/

**Comment by shirshendu** [comment]
@GowthamShanmugam Commits need to be signed.
https://help.github.com/articles/signing-commits-using-gpg/
https://help.github.com/articles/about-gpg/

You'll need to amend this commit with a signature, and force push to your branch.
(Github will need this PR to be approved again once a signed commit is pushed @shtripat)

**Pull request merged**
